spring:
  application:
    name: pixai-api

  data:
    mongodb:
      uri: mongodb://localhost:27017

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info